config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :yachts do
    resources :bookings, only: [:create]
    collection do
      get 'myyachts'
    end
  end

  resources :bookings, only: [:index, :update]
  resources :ports, only: [:show]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>

  <div class="grid grid-width">
    <div class="logo">
      <div><%= image_tag "logowhite.png", height: 150 %></div>
    </div>
    <div class="contact">
<!--       <p>Available in the best ports in the world</p> -->
      <h3>Contact</h3>
      <p><i class="fas fa-phone">&nbsp;</i> 01 23 45 67 89</p>
      <p><i class="fas fa-map-marked-alt">&nbsp;</i>19 rue de la Capitainerie 06600 Antibes</p>
      <p><i class="fas fa-at">&nbsp;</i>contact@myphocea.com</p>
    </div>
    <div class="social">
      <p>Follow us</p>
      <div class="social-network">
        <a href="https://www.facebook.com/"><i class="fab fa-facebook"></i></a>
        <a href="https://www.twitter.com/"><i class="fab fa-twitter"></i></a>
        <a href="https://www.instagram.com/"><i class="fab fa-instagram"></i></a>
        <a href="https://www.linkedin.com/"><i class="fab fa-linkedin"></i></a>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->

  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "My bookings", bookings_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "My yachts", myyachts_yachts_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= cl_image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li><a href="#">My profile</a></li>
            <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to "Sign up", new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Sign in", new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>
</div>