config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :yachts do
    resources :bookings, only: [:create]
    collection do
      get 'myyachts'
    end
  end

  resources :bookings, only: [:index, :update]
  resources :ports, only: [:show]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/_banner.html.erb
<div class="banner">
  <div class="container">
    <h1 class="text-center">Change your yacht as you change your mind</h1>
    <p class="text-center">Lease yours somewhere. Rent one anywhere.</p>
  </div>
  <%= render 'yachts/searchform' %>
</div>

app/views/pages/_carddashboard.html.erb
<% yachts.each do |yacht| %>
  <div class="card-dashboard">
    <div class="card-category" >
      <div class="card-image" style="background-image: linear-gradient(rgba(0,0,0,0), rgba(0,0,0,0)), url('<%= cl_image_path yacht.photo1 %>')">
        <ul class="list-inline">
          <li class="list-inline-item"></li>
        </ul>
      </div>
      <div class="card-description">
          <ul class="name-edit">
            <li> <h2><%= yacht.name %></h2></li>
          <li>Edit&nbsp; <%= link_to "<i class='fas fa-pen flaticon'></i>".html_safe, edit_yacht_path(yacht.id) %></li>
          </ul>
        <ul class="list-inline">
          <li class="list-inline-item"><i class="fas fa-anchor"></i>&nbsp;<%= yacht.port.address %></li>
          <li class="list-inline-item"><i class="fas fa-users"></i>&nbsp;<%= yacht.passengers_capacity %></li>
          <li class="list-inline-item"><i class="fas fa-euro-sign"></i>&nbsp;<%= number_with_delimiter(yacht.price, separator: " ") %></li>
        </ul>
      </div>
    </div>
    <!-- WHEN NO YACHT BOOKINGS -->
    <% if yacht.bookings.count == 0 %>
      <div class="no-bookings">
        <div class="no-bookings-items">
          <i class="far fa-clock fa-5x flaticon"></i>
        </div>
        <div class="no-bookings-items">
          <p><em>You don't have any booking requests yet for this yacht, would you like to make some changes ?</em></p>
        </div>
        <div class="no-bookings-items">
          <%= link_to "Edit this yacht".html_safe, edit_yacht_path(yacht.id), class: "btn btn-validation btn-booking" %>
        </div>
      </div>
    <!-- WHEN AT LEAST 1 YACHT BOOKINGS -->
    <% else %>
      <ul class="bookings-by-yachts">
        <% yacht.bookings.each do |booking| %>
          <% total = (booking.end_date - booking.start_date)*booking.yacht.price %></p>
          <li class="booking-user">
            <div class="booking-userpicture">
              <%= cl_image_tag booking.user.photo, class: "avatarmyyatchs" %>
            </div>
            <div class="book-name-date">
              <h3><%= booking.user.first_name %> <%= booking.user.last_name %></h3>
              <p>From <%= booking.start_date.to_s(:rfc822) %> to <%= booking.end_date.to_s(:rfc822) %></p>
            </div>
            <div class="booking-status">
             <% if booking.status == 'Approved'%>
                <p class="approved"><%= booking.status.capitalize %></p>
              <% elsif booking.status == 'Declined' %>
                <p class="declined"><%= booking.status.capitalize %></p>
              <% else %>
                <p class="pending"><%= booking.status.capitalize %></p>
              <% end %>
              <p>
                <%= number_with_delimiter((total*1.2).to_i, separator: " ") %> <em><i class="fas fa-euro-sign"></i>&nbsp;&nbsp;inc. tax.</em>
              </p>
            </div>
            <% if booking.status == "Pending" %>
              <div class="status-buttons">
                <%= link_to "Approve", booking_path(booking, booking: {status: 'Approved'}), method: :put, class: "btn-approve"%><%= link_to "Decline", booking_path(booking, booking: {status: 'Declined'}), method: :put, class: "btn-decline" %>
              </div>
            <% end %>
          </li>
        <% end %>
      </ul>
    <% end %>
  </div>
<% end %>

app/views/pages/_cardport.html.erb
<div class="cards">
  <% ports.each do |port| %>
    <div class="card-category">
      <%= link_to port_path(port) do %>
        <div class="card-image" style="background-image: linear-gradient(rgba(0,0,0,0), rgba(0,0,0,0)), url('<%= cl_image_path port.photo %>')">
          <ul class="list-inline">
            <li class="list-inline-item"></li>
          </ul>
        </div>
        <div class="card-description">
          <h2><%= port.name %></h2>
          <ul class="list-inline">
            <li class="list-inline-item"><i class="fas fa-anchor"></i>&nbsp;<%= port.address %></li>
             <li class="list-inline-item"><i class="fas fa-ship"></i>&nbsp;<%= port.yachts.count %></li>
          </ul>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/pages/_cards.html.erb
<div class="cards">
  <% yachts.each do |yacht| %>
    <div class="card-category">
      <%= link_to yacht_path(yacht) do %>
        <div class="card-image" style="background-image: linear-gradient(rgba(0,0,0,0), rgba(0,0,0,0)), url('<%= cl_image_path yacht.photo1 %>')">
          <ul class="list-inline">
            <li class="list-inline-item"></li>
          </ul>
        </div>
        <div class="card-description">
          <h2><%= yacht.name %></h2>
          <ul class="list-inline">
            <li class="list-inline-item"><i class="fas fa-anchor"></i>&nbsp;<%= yacht.port.address %></li>
            <li class="list-inline-item"><i class="fas fa-users"></i>&nbsp;<%= yacht.passengers_capacity %></li>
            <li class="list-inline-item"><i class="fas fa-euro-sign"></i>&nbsp;<%= number_with_delimiter(yacht.price, separator: " ") %>/day</li>
          </ul>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/pages/_infowindow.html.erb
<div> <%= link_to port_path(port) do %>
  <%= cl_image_tag port.photo, height: 140, width: 180, crop: :fill %> </div>
  <% end %>
<div><strong><%= port.address %></strong></div>
<div><%= port.name %></div>
<div>number of yachts:&nbsp;<%= port.yachts.count %></div>

app/views/pages/home.html.erb
<%= render 'banner' %>
<div class="container" id="search-result">
  <% if @yachts.size == Yacht.count %>
    <h1 class="text-center">Our selection of world-class yachts...</h1>
    <%= render 'pages/cards', yachts: @yachts.sample(9) %>
  <% else %>
    <h1 class="text-center">Your selection of yachts</h1>
    <%= render 'pages/cards', yachts: @yachts.limit(9) %>
  <% end %>
  <h1 class="text-center">...available across the world's oceans</h1>
  <div
    id="map"
    style="width: 100%;
    height: 600px;"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
  ></div>
  <h1 class="text-center">Check-out current hot spots!</h1>
  <%= render 'pages/cardport', ports: @ports.sample(3) %>
</div>